### ISSUE TITLE
Group Project React-Redux

### ISSUE THREAD

**Issue by RicardoEgas** [RicardoEgas/Space-Travelers#25]
[Space-Travelers](https://github.com/RicardoEgas/Space-Travelers)

3 people.

**Comment by shahadat3669** [comment]
Hi @balatstar, @RicardoEgas, @MenendezON, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ All cards are assigned to team members
✅ Has information about the number of people in their group.
✅ Students' board is a copy of [template board](https://github.com/microverseinc/curriculum-react-redux/projects/1).


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- [Optional] Well done on providing the GitHub repository link. However, kindly note that the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=In%20its%20description%2C%20paste%20a%20link%20to%20your%20GitHub%20project.) call for sharing the project link, not the repository link. I recommend ensuring that you adhere closely to the project requirements in the future. Keep up the good work and best of luck with your ongoing efforts!

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
